// packages/dx-vue-demos/src/template-overriding.vue
<template>
  <div>
    <PluginHost>
      <Template name="root">
        First template
      </Template>
      <Template name="root">
        <div>
          <TemplatePlaceholder></TemplatePlaceholder>
          <br />
          Second template
        </div>
      </Template>
    </PluginHost>
  </div>
</template>

<script>
import { PluginHost, Template, TemplatePlaceholder } from '@devexpress/dx-vue-core';

export default {
  components: {
    PluginHost,
    Template,
    TemplatePlaceholder,
  }
};
</script>

<style>
</style>

// packages/dx-react-demos/src/demo-sources/core-template/bootstrap3/template-overriding.jsx
import React from 'react';
import {
  PluginHost,
  Plugin,
  Template,
  TemplatePlaceholder,
} from '@devexpress/dx-react-core';

const Plugin1 = () => (
  <Plugin>
    <Template name="root">
      List of cities:
      <ul>
        <TemplatePlaceholder name="city" params={{ title: 'New York' }} />
        <TemplatePlaceholder name="city" params={{ title: 'Paris' }} />
        <TemplatePlaceholder name="city" params={{ title: 'Tokyo' }} />
      </ul>
    </Template>
    <Template name="city">
      {({ title }) => (
        <li>{title}</li>
      )}
    </Template>
  </Plugin>
);

const Plugin2 = () => (
  <Plugin>
    <Template name="city">
      {({ title }) => (title === 'Paris' ? (
        <li><b>{title}</b></li>
      ) : (
        <TemplatePlaceholder />
      ))}
    </Template>
  </Plugin>
);

export default () => (
  <PluginHost>
    <Plugin1 />
    <Plugin2 />
  </PluginHost>
);
