// packages/dx-vue-demos/src/template-parameters.vue
<template>
  <div>
    <PluginHost>
      <Template name="root">
        <ul>
          <TemplatePlaceholder
            v-for="(item, index) in items" :key="index"
            name="item"
            :params="item"
          ></TemplatePlaceholder>
        </ul>
      </Template>
      <Template name="item">
        <template slot-scope="item">
          <li>{{ item }}</li>
        </template>
      </Template>
    </PluginHost>
  </div>
</template>

<script>
import { PluginHost, Template, TemplatePlaceholder } from '@devexpress/dx-vue-core';

export default {
  data() {
    return {
      items: [1, 2, 3],
    };
  },
  components: {
    PluginHost,
    Template,
    TemplatePlaceholder,
  }
};
</script>

<style>
</style>

// packages/dx-react-demos/src/demo-sources/core-template/bootstrap3/template-parameters.jsx
import React from 'react';
import {
  PluginHost,
  PluginContainer,
  Template,
  TemplatePlaceholder,
} from '@devexpress/dx-react-core';

const Plugin = () => (
  <PluginContainer>
    <Template name="root">
      List of cities:
      <ul>
        <TemplatePlaceholder name="city" params={{ title: 'New York' }} />
        <TemplatePlaceholder name="city" params={{ title: 'Paris' }} />
        <TemplatePlaceholder name="city" params={{ title: 'Tokyo' }} />
      </ul>
    </Template>
    <Template name="city">
      {({ title }) => (
        <li>{title}</li>
      )}
    </Template>
  </PluginContainer>
);

export default () => (
  <PluginHost>
    <Plugin />
  </PluginHost>
);
