// packages/dx-react-demos/src/demo-sources/core-template/bootstrap3/template-placeholder.jsx
import React from 'react';
import {
  PluginHost,
  Plugin,
  Template,
  TemplatePlaceholder,
} from '@devexpress/dx-react-core';

const Plugin1 = () => (
  <Plugin>
    <Template name="root">
      Root content:
      {' '}
      <TemplatePlaceholder name="content" />
    </Template>
  </Plugin>
);

const Plugin2 = () => (
  <Plugin>
    <Template name="content">
      sample text
    </Template>
  </Plugin>
);

export default () => (
  <PluginHost>
    <Plugin1 />
    <Plugin2 />
  </PluginHost>
);

// packages/dx-vue-demos/src/template-placeholder.vue
<template>
  <div>
    <PluginHost>
      <Template name="root">
        <TemplatePlaceholder name="nested"></TemplatePlaceholder>
      </Template>
      <Template name="nested">
        Hello, from nested template!
      </Template>
    </PluginHost>
  </div>
</template>

<script>
import { PluginHost, Template, TemplatePlaceholder } from '@devexpress/dx-vue-core';

export default {
  components: {
    PluginHost,
    Template,
    TemplatePlaceholder,
  }
};
</script>

<style>
</style>
