// packages/dx-react-grid-demos/src/demo-sources/core-getter/bootstrap3/value-getter.jsx
import React, { useState } from 'react';
import {
  PluginHost, Plugin, Getter, Template, TemplateConnector,
} from '@devexpress/dx-react-core';

export default () => {
  const [tasks] = useState([
    { title: 'call mom', done: false },
    { title: 'send letters to partners', done: false },
    { title: 'buy milk', done: true },
    { title: 'rent a car', done: false },
  ]);

  return (
    <TasksList tasks={tasks}>
      {/* Here we may add another plugins */}
    </TasksList>
  );
};

const TasksList = ({ children, ...restProps }) => (
  <PluginHost>
    <TasksListCore {...restProps} />
    {children}
  </PluginHost>
);

const TasksListCore = ({ tasks }) => (
  <Plugin>
    <Getter name="tasks" value={tasks} />
    <Template name="root">
      <ul>
        <TaskIndexer />
      </ul>
    </Template>
  </Plugin>
);

const TaskIndexer = () => (
  <TemplateConnector>
    {({ tasks }) => (tasks.map(({ title, done }, index) => (
      <li
        key={index} // eslint-disable-line react/no-array-index-key
        style={{ textDecoration: done ? 'line-through' : '' }}
      >
        {title}
      </li>
    )))}
  </TemplateConnector>
);

// packages/dx-vue-demos/src/value-getter.vue
<template>
  <TasksList v-bind:tasks="tasks">
    <!-- Here we may add another plugins -->
  </TasksList>
</template>

<script>
import { PluginHost, Plugin, Getter, Template, TemplateConnector } from '@devexpress/dx-vue-core';

const TasksList = {
  props: { tasks: {} },
  render() {
    return (
      <PluginHost>
        <TasksListCore tasks={this.tasks} />
        {this.$slots.default}
      </PluginHost>
    );
  },
};

const TasksListCore = {
  components: { Template, Getter },
  props: { tasks: {} },
  render() {
    return (
      <Plugin>
        <Getter name="tasks" value={this.tasks} />
        <Template name="root">
          <TemplateConnector>
            {({ getters: { tasks } }) => (
              <ul>
                {tasks.map(({ title, done }, index) => (
                  <li
                    key={index}
                    style={{ textDecoration: done ? 'line-through' : '' }}
                  >
                    {title}
                  </li>
                ))}
              </ul>
            )}
          </TemplateConnector>
        </Template>
      </Plugin>
    );
  },
};

const TaskIndexer = {
  components: { TemplateConnector },
  render() {
    return (
      <TemplateConnector>
        {({ getters: { tasks } }) => (
          <ul>
            {tasks.map(({ title, done }, index) => (
              <li
                key={index}
                style={{ textDecoration: done ? 'line-through' : '' }}
              >
                {title}
              </li>
            ))}
          </ul>
        )}
      </TemplateConnector>
    );
  },
};

export default {
  components: {
    TasksList,
  },
  data() {
    return {
      tasks: [
        { title: 'call mom', done: false },
        { title: 'send letters to partners', done: false },
        { title: 'buy milk', done: true },
        { title: 'rent a car', done: false },
      ],
    }
  },
};
</script>

<style>
</style>
