// packages/dx-vue-demos/src/plugin-component.vue
<template>
  <TasksList v-bind:tasks="tasks">
    <!-- Here we may add other plugins -->
  </TasksList>
</template>

<script>
import Vue from 'vue';
import { PluginHost, Plugin, Template } from '@devexpress/dx-vue-core';

const TasksListCore = {
  components: {
    Template,
    Plugin,
  },
  props: ['tasks'],
  render() {
    return (
      <Plugin>
        <Template name="root">
          <ul>
            {this.tasks.map(({ title, done }, index) =>
              <li
                key={index}
                style={{ textDecoration: done ? 'line-through' : '' }}
              >
                {title}
              </li>
            )}
          </ul>
        </Template>
      </Plugin>
    );
  },
};

const TasksList = {
  components: {
    PluginHost,
    TasksListCore,
  },
  props: ['tasks'],
  render() {
    return (
      <PluginHost>
        <TasksListCore tasks={this.tasks} />
      </PluginHost>
    );
  },
};

export default {
  components: {
    TasksList,
  },
  data() {
    return {
      tasks: [
        { title: 'call mom', done: false },
        { title: 'send letters to partners', done: false },
        { title: 'buy milk', done: true },
        { title: 'rent a car', done: false },
      ],
    }
  },
};
</script>

<style>
</style>

// packages/dx-react-demos/src/demo-sources/core-basic/bootstrap3/plugin-component.jsx
import * as React from 'react';
import { PluginHost, Plugin, Template } from '@devexpress/dx-react-core';

export default class Demo extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      tasks: [
        { title: 'call mom', done: false },
        { title: 'send letters to partners', done: false },
        { title: 'buy milk', done: true },
        { title: 'rent a car', done: false },
      ],
    };
  }
  render() {
    const { tasks } = this.state;

    return (
      <TasksList
        tasks={tasks}
      >
        {/* Here we may add another plugins */}
      </TasksList>
    );
  }
}

const TasksList = ({ children, ...restProps }) => (
  <PluginHost>
    <TasksListCore {...restProps} />
    {children}
  </PluginHost>
);

const TasksListCore = ({ tasks }) => (
  <Plugin>
    <Template name="root">
      <ul>
        {tasks.map(({ title, done }, index) => (
          <li
            key={index} // eslint-disable-line react/no-array-index-key
            style={{ textDecoration: done ? 'line-through' : '' }}
          >
            {title}
          </li>
        ))}
      </ul>
    </Template>
  </Plugin>
);
