// packages/dx-vue-demos/src/computed-getter.vue
<template>
 <TasksList v-bind:tasks="tasks">
    <TasksFilter v-bind:done="false"></TasksFilter>
  </TasksList>
</template>

<script>
import { PluginHost, Getter, Template, TemplateConnector } from '@devexpress/dx-vue-core';

const TasksList = {
  props: { tasks: {} },
  render() {
    return (
      <PluginHost>
        <TasksListCore tasks={this.tasks} />
        {this.$slots.default}
      </PluginHost>
    );
  },
};

const TasksListCore = {
  props: { tasks: {} },
  render() {
    return (
      // <Plugin>
      <div>
        <Getter name="tasks" value={this.tasks} />
        <Template name="root">
          <TemplateConnector>
            {({ getters: { tasks: processedTasks } }) => (
              <ul>
                {processedTasks.map(({ title, done }, index) => (
                  <li
                    key={index}
                    style={{ textDecoration: done ? 'line-through' : '' }}
                  >
                    {title}
                  </li>))}
              </ul>
            )}
          </TemplateConnector>
        </Template>
      </div>
      // </Plugin>
    );
  },
};

const TasksFilter = {
  components: { Getter },
  props: { done: {} },
  render() {
    return (
      // <Plugin>
        <Getter
          name="tasks"
          computed={({ tasks }) => tasks.filter(task => this.done === null || task.done === this.done)}
        />
      // </Plugin>
    );
  },
};

export default {
  components: {
    TasksList,
    TasksFilter,
  },
  data() {
    return {
      tasks: [
        { title: 'call mom', done: false },
        { title: 'send letters to partners', done: false },
        { title: 'buy milk', done: true },
        { title: 'rent a car', done: false },
      ],
    }
  },
};
</script>

<style>
</style>

// packages/dx-react-grid-demos/src/demo-sources/core-getter/bootstrap3/computed-getter.jsx
import React, { useState } from 'react';
import {
  PluginHost, Plugin, Getter, Template, TemplateConnector,
} from '@devexpress/dx-react-core';

export default () => {
  const [tasks] = useState([
    { title: 'call mom', done: false },
    { title: 'send letters to partners', done: false },
    { title: 'buy milk', done: true },
    { title: 'rent a car', done: false },
  ]);

  return (
    <TasksList tasks={tasks}>
      <TasksFilter done={false} />
    </TasksList>
  );
};

const TasksList = ({ children, ...restProps }) => (
  <PluginHost>
    <TasksListCore {...restProps} />
    {children}
  </PluginHost>
);

const TasksListCore = ({ tasks }) => (
  <Plugin>
    <Getter name="tasks" value={tasks} />
    <Template name="root">
      <ul>
        <TemplateConnector>
          {({ tasks: processedTasks }) => (processedTasks.map(({ title, done }, index) => (
            <li
              key={index} // eslint-disable-line react/no-array-index-key
              style={{ textDecoration: done ? 'line-through' : '' }}
            >
              {title}
            </li>
          )))}
        </TemplateConnector>
      </ul>
    </Template>
  </Plugin>
);

const TasksFilter = ({ done }) => (
  <Plugin>
    <Getter
      name="tasks"
      computed={({ tasks }) => tasks.filter(task => done === null || task.done === done)}
    />
  </Plugin>
);
